# [START cloudbuild]
steps:
# This step destroys terraform infra
- id: 'tf init'
  name: 'hashicorp/terraform:latest'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      terraform destroy -var-file=dev.tfvars

options:
  logging: CLOUD_LOGGING_ONLY
# [END cloudbuild-trigger-cd]